server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/graduation?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456

  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      timeout: 5s

mybatis-plus:

  # Mapper XML路径
  mapper-locations: classpath*:mapper/**/*.xml

  # 实体类别名扫描
  type-aliases-package: com.gjx.gpms.*.entity

  configuration:

    # 控制台SQL日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

  global-config:
    db-config:

      # 逻辑删除字段
      logic-delete-field: isDeleted

      # 已删除
      logic-delete-value: 1

      # 未删除
      logic-not-delete-value: 0

logging:
  level:

    # 项目日志级别
    com.gjx.gpms: debug