server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/graduation_management?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: "000000"
    driver-class-name: com.mysql.cj.jdbc.Driver

jwt:
    secret: gjxgjxgjxgjxgjxgjxgjxgjxgjxgjxnb  # 至少32个字符
    expiration: 86400000